# FIXME
# Ansible's apt_repository module doesn't work correcty with Linux Mint,
# see https://github.com/ansible/ansible/issues/4587
# Also, the filenames that are checked for existence are hardcoded :(

- name: Install latest versions of apt packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - build-essential
    - zsh
    - wget
    - unzip
    - firefox
    - git
    - gitk
    - gparted
    - htop
    - openjdk-8-jdk
    - openssh-server
    - tmux
    - vim
    - vim-gnome
    - vlc
    - xbacklight   # changing screen brightness
    - xsel   # copying and pasting from middle-mouse-button clipboard
    - libssl-dev # for R
    - libcurl4-openssl-dev # for R
    - gdebi
    - nautilus-dropbox # for dropbox
    - libxml2-dev # r from here below
    - r-base-dev
    - libgdal-dev # gdal for sf R
    - libproj-dev # gdal for sf R
    - libudunits2-dev # sf for R
#  sudo: yes

# TODO
# I think this is not needed anymore...
#- name: Finish DVD decryption installation
#  shell: /usr/share/doc/libdvdread4/install-css.sh
#  sudo: yes

