- include: install-docker.yml

#- include: install-timeshift.yml
#
#- include: install-chrome.yml
#
#- include: install-dropbox.yml
#
#- include: install-rstudio.yml
#
#- include: install-atom.yml
#
#- include: install-packages.yml
#
#- include: install-packages.yml

#- name: check whether dropbox is installed
#  shell: which dropbox
#  register: dropbox_check
#  failed_when: dropbox_check.rc > 1
#  changed_when: dropbox_check.rc == 1
#
#- include: install-dropbox.yml
#  when: dropbox_check.rc == 1

